// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiDpgwbgFmDajeHdw534Xfnv2xcRoJBdw',
    appId: '1:21779768245:web:213dac4783899dc0f66ffc',
    messagingSenderId: '21779768245',
    projectId: 'skripsipresensifcm',
    authDomain: 'skripsipresensifcm.firebaseapp.com',
    storageBucket: 'skripsipresensifcm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XVxceRHA75CxxKmbYjJwNlJLIWw5wTA',
    appId: '1:21779768245:android:a692fc5a75f915a5f66ffc',
    messagingSenderId: '21779768245',
    projectId: 'skripsipresensifcm',
    storageBucket: 'skripsipresensifcm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-v-CZaWRV7vbKibBDLy0DApC6AhPb0UU',
    appId: '1:21779768245:ios:1727e1ce13eb2cccf66ffc',
    messagingSenderId: '21779768245',
    projectId: 'skripsipresensifcm',
    storageBucket: 'skripsipresensifcm.appspot.com',
    iosClientId: '21779768245-dlc2ajrhmo63545raond6q6bcp0lne2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiPresensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-v-CZaWRV7vbKibBDLy0DApC6AhPb0UU',
    appId: '1:21779768245:ios:1727e1ce13eb2cccf66ffc',
    messagingSenderId: '21779768245',
    projectId: 'skripsipresensifcm',
    storageBucket: 'skripsipresensifcm.appspot.com',
    iosClientId: '21779768245-dlc2ajrhmo63545raond6q6bcp0lne2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiPresensi',
  );
}
